# Generated by Django 2.0.6 on 2019-09-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_siteuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='photo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
